# Classifying Penguins with Keras

In [1]:
import pandas as pd
from sklearn import preprocessing
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
from palmerpenguins import load_penguins

penguins = load_penguins().dropna().sample(frac=1, random_state=42)
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
30,Adelie,Dream,39.5,16.7,178.0,3250.0,female,2007
320,Chinstrap,Dream,50.9,17.9,196.0,3675.0,female,2009
79,Adelie,Torgersen,42.1,19.1,195.0,4000.0,male,2008
202,Gentoo,Biscoe,46.6,14.2,210.0,4850.0,female,2008
63,Adelie,Biscoe,41.1,18.2,192.0,4050.0,male,2008

In [3]:
penguins_x = pd.concat(
    [
        penguins[["body_mass_g", "bill_length_mm", "bill_depth_mm", "flipper_length_mm"]],
        pd.get_dummies(penguins["sex"]),
    ],
    axis=1,
)

# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
30,3250.0,39.5,16.7,178.0,True,False
320,3675.0,50.9,17.9,196.0,True,False
79,4000.0,42.1,19.1,195.0,False,True
202,4850.0,46.6,14.2,210.0,True,False
63,4050.0,41.1,18.2,192.0,False,True
...,...,...,...,...,...,...
195,4750.0,49.6,15.0,216.0,False,True
77,3900.0,37.2,19.4,184.0,False,True
112,3200.0,39.7,17.7,193.0,True,False
281,3950.0,45.2,17.8,198.0,True,False
108,3175.0,38.1,17.0,181.0,True,False

In [4]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)

In [7]:
penguins_y = penguins["species"]
penguins_y = penguins_y.astype("category").cat.codes.to_numpy()

In [8]:
# construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation="relu")(inputs)
x = layers.Dense(5, activation="relu")(x)
x = layers.Dense(3, activation="relu")(x)
outputs = layers.Dense(3, activation="softmax")(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [9]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(
    scaled_penguins_x, penguins_y, batch_size=64, epochs=100, validation_split=0.1
)

scores = model.evaluate(scaled_penguins_x, penguins_y, verbose=2)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/100

C:\miniforge3\envs\machine-learning\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.4381 - loss: 1.0972 - val_accuracy: 0.3824 - val_loss: 1.0950
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4381 - loss: 1.0938 - val_accuracy: 0.3824 - val_loss: 1.0924
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4415 - loss: 1.0913 - val_accuracy: 0.3824 - val_loss: 1.0907

C:\miniforge3\envs\machine-learning\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4448 - loss: 1.0885 - val_accuracy: 0.4118 - val_loss: 1.0880
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4448 - loss: 1.0844 - val_accuracy: 0.4118 - val_loss: 1.0841
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4582 - loss: 1.0804 - val_accuracy: 0.4118 - val_loss: 1.0805
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4515 - loss: 1.0765 - val_accuracy: 0.3824 - val_loss: 1.0771
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 1.0726 - val_accuracy: 0.3824 - val_loss: 1.0738
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4415 - loss: 1.0688 - val_accuracy: 0.3824 - val_loss: 1.0707
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 1.0652 - val_accuracy: 0.3824 - val_loss: 1.0680
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4448 - loss: 1.0614 - val_accuracy: 0.3824 - val_loss: 1.0648
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 1.0574 - val_accuracy: 0.3824 - val_loss: 1.0612
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4448 - loss: 1.0538 - val_accuracy: 0.3824 - val_loss: 1.0576
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4448 - loss: 1.0498 - val_accuracy: 0.3824 - val_loss: 1.0542
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4448 - loss: 1.0462 - val_accuracy: 0.3824 - val_loss: 1.0508
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 1.0426 - val_accuracy: 0.3824 - val_loss: 1.0468
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4448 - loss: 1.0387 - val_accuracy: 0.3824 - val_loss: 1.0431
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4448 - loss: 1.0345 - val_accuracy: 0.3824 - val_loss: 1.0387
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4448 - loss: 1.0261 - val_accuracy: 0.3824 - val_loss: 1.0254
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4482 - loss: 1.0102 - val_accuracy: 0.3824 - val_loss: 1.0121
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4482 - loss: 0.9986 - val_accuracy: 0.3824 - val_loss: 1.0072
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4615 - loss: 0.9921 - val_accuracy: 0.3824 - val_loss: 1.0036
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4649 - loss: 0.9865 - val_accuracy: 0.3824 - val_loss: 0.9993
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4749 - loss: 0.9811 - val_accuracy: 0.4118 - val_loss: 0.9957
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4816 - loss: 0.9761 - val_accuracy: 0.4118 - val_loss: 0.9919
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5117 - loss: 0.9711 - val_accuracy: 0.4118 - val_loss: 0.9875
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5184 - loss: 0.9663 - val_accuracy: 0.4118 - val_loss: 0.9834
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5452 - loss: 0.9624 - val_accuracy: 0.4412 - val_loss: 0.9804
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5686 - loss: 0.9572 - val_accuracy: 0.4706 - val_loss: 0.9765
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5819 - loss: 0.9526 - val_accuracy: 0.4706 - val_loss: 0.9723
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5886 - loss: 0.9485 - val_accuracy: 0.4706 - val_loss: 0.9690
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6087 - loss: 0.9441 - val_accuracy: 0.5294 - val_loss: 0.9643
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6421 - loss: 0.9392 - val_accuracy: 0.5882 - val_loss: 0.9606
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6455 - loss: 0.9346 - val_accuracy: 0.5882 - val_loss: 0.9569
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6990 - loss: 0.9304 - val_accuracy: 0.6471 - val_loss: 0.9529
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7391 - loss: 0.9256 - val_accuracy: 0.6471 - val_loss: 0.9486
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7258 - loss: 0.9208 - val_accuracy: 0.6765 - val_loss: 0.9452
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7425 - loss: 0.9159 - val_accuracy: 0.7059 - val_loss: 0.9398
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7525 - loss: 0.9108 - val_accuracy: 0.7353 - val_loss: 0.9359
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7826 - loss: 0.9058 - val_accuracy: 0.7941 - val_loss: 0.9302
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7960 - loss: 0.9011 - val_accuracy: 0.7941 - val_loss: 0.9259
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7960 - loss: 0.8960 - val_accuracy: 0.7941 - val_loss: 0.9220
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8127 - loss: 0.8914 - val_accuracy: 0.7941 - val_loss: 0.9172
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8027 - loss: 0.8854 - val_accuracy: 0.7941 - val_loss: 0.9129
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8127 - loss: 0.8806 - val_accuracy: 0.8235 - val_loss: 0.9075
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8261 - loss: 0.8758 - val_accuracy: 0.8235 - val_loss: 0.9037
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8227 - loss: 0.8713 - val_accuracy: 0.8235 - val_loss: 0.8989
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8328 - loss: 0.8659 - val_accuracy: 0.7941 - val_loss: 0.8947
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8328 - loss: 0.8602 - val_accuracy: 0.8235 - val_loss: 0.8902
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8428 - loss: 0.8555 - val_accuracy: 0.7941 - val_loss: 0.8844
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8395 - loss: 0.8501 - val_accuracy: 0.8235 - val_loss: 0.8795
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8428 - loss: 0.8445 - val_accuracy: 0.8235 - val_loss: 0.8733
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8462 - loss: 0.8389 - val_accuracy: 0.8235 - val_loss: 0.8691
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8462 - loss: 0.8340 - val_accuracy: 0.8529 - val_loss: 0.8626
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8462 - loss: 0.8274 - val_accuracy: 0.8235 - val_loss: 0.8580
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8528 - loss: 0.8221 - val_accuracy: 0.8235 - val_loss: 0.8533
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8395 - loss: 0.8161 - val_accuracy: 0.8529 - val_loss: 0.8465
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8428 - loss: 0.8105 - val_accuracy: 0.8529 - val_loss: 0.8413
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8395 - loss: 0.8050 - val_accuracy: 0.8529 - val_loss: 0.8349
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8395 - loss: 0.7987 - val_accuracy: 0.8529 - val_loss: 0.8295
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8395 - loss: 0.7927 - val_accuracy: 0.8235 - val_loss: 0.8245
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8428 - loss: 0.7869 - val_accuracy: 0.8235 - val_loss: 0.8183
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8462 - loss: 0.7804 - val_accuracy: 0.8235 - val_loss: 0.8118
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8462 - loss: 0.7741 - val_accuracy: 0.8235 - val_loss: 0.8044
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8528 - loss: 0.7682 - val_accuracy: 0.8235 - val_loss: 0.7983
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8562 - loss: 0.7621 - val_accuracy: 0.8235 - val_loss: 0.7924
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8528 - loss: 0.7555 - val_accuracy: 0.8235 - val_loss: 0.7871
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8495 - loss: 0.7495 - val_accuracy: 0.8235 - val_loss: 0.7803
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8528 - loss: 0.7436 - val_accuracy: 0.8235 - val_loss: 0.7747
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8528 - loss: 0.7370 - val_accuracy: 0.8235 - val_loss: 0.7676
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8528 - loss: 0.7309 - val_accuracy: 0.8235 - val_loss: 0.7614
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8528 - loss: 0.7243 - val_accuracy: 0.8235 - val_loss: 0.7567
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8528 - loss: 0.7182 - val_accuracy: 0.8235 - val_loss: 0.7500
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8528 - loss: 0.7120 - val_accuracy: 0.8235 - val_loss: 0.7435
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8562 - loss: 0.7056 - val_accuracy: 0.8235 - val_loss: 0.7380
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8495 - loss: 0.7003 - val_accuracy: 0.8235 - val_loss: 0.7326
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8528 - loss: 0.6935 - val_accuracy: 0.8235 - val_loss: 0.7252
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8562 - loss: 0.6875 - val_accuracy: 0.8235 - val_loss: 0.7200
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8528 - loss: 0.6808 - val_accuracy: 0.8235 - val_loss: 0.7143
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8562 - loss: 0.6746 - val_accuracy: 0.8235 - val_loss: 0.7074
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8562 - loss: 0.6693 - val_accuracy: 0.8235 - val_loss: 0.7011
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8562 - loss: 0.6616 - val_accuracy: 0.8235 - val_loss: 0.6948
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8562 - loss: 0.6552 - val_accuracy: 0.8235 - val_loss: 0.6868
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8562 - loss: 0.6495 - val_accuracy: 0.8235 - val_loss: 0.6821
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8528 - loss: 0.6430 - val_accuracy: 0.8235 - val_loss: 0.6746
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8562 - loss: 0.6372 - val_accuracy: 0.8235 - val_loss: 0.6691
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8595 - loss: 0.6304 - val_accuracy: 0.8235 - val_loss: 0.6638
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8595 - loss: 0.6240 - val_accuracy: 0.8235 - val_loss: 0.6570
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8595 - loss: 0.6180 - val_accuracy: 0.7941 - val_loss: 0.6521
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8595 - loss: 0.6126 - val_accuracy: 0.8235 - val_loss: 0.6456
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8595 - loss: 0.6061 - val_accuracy: 0.8235 - val_loss: 0.6378
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8595 - loss: 0.6007 - val_accuracy: 0.8235 - val_loss: 0.6328
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8562 - loss: 0.5943 - val_accuracy: 0.8235 - val_loss: 0.6275
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8629 - loss: 0.5881 - val_accuracy: 0.8235 - val_loss: 0.6208
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8595 - loss: 0.5822 - val_accuracy: 0.8235 - val_loss: 0.6137
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8595 - loss: 0.5761 - val_accuracy: 0.8235 - val_loss: 0.6080
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8562 - loss: 0.5706 - val_accuracy: 0.8235 - val_loss: 0.6014
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8595 - loss: 0.5644 - val_accuracy: 0.8235 - val_loss: 0.5954
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8595 - loss: 0.5588 - val_accuracy: 0.8235 - val_loss: 0.5892
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8595 - loss: 0.5525 - val_accuracy: 0.8235 - val_loss: 0.5835
11/11 - 0s - 2ms/step - accuracy: 0.8559 - loss: 0.5519

In [10]:
model_logit_false = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_false.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_false.fit(
    scaled_penguins_x, penguins_y, batch_size=64, epochs=100, validation_split=0.1
)

scores = model_logit_false.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8562 - loss: 0.5453 - val_accuracy: 0.8235 - val_loss: 0.5719
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8562 - loss: 0.5343 - val_accuracy: 0.8235 - val_loss: 0.5642
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8595 - loss: 0.5273 - val_accuracy: 0.8235 - val_loss: 0.5581
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8595 - loss: 0.5204 - val_accuracy: 0.8235 - val_loss: 0.5519
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8595 - loss: 0.5160 - val_accuracy: 0.8235 - val_loss: 0.5476
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8629 - loss: 0.5095 - val_accuracy: 0.8235 - val_loss: 0.5415
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8595 - loss: 0.5047 - val_accuracy: 0.8235 - val_loss: 0.5358
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8629 - loss: 0.4997 - val_accuracy: 0.8235 - val_loss: 0.5308
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8629 - loss: 0.4941 - val_accuracy: 0.8235 - val_loss: 0.5268
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8629 - loss: 0.4889 - val_accuracy: 0.8235 - val_loss: 0.5208
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8595 - loss: 0.4845 - val_accuracy: 0.8235 - val_loss: 0.5157
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8662 - loss: 0.4793 - val_accuracy: 0.8235 - val_loss: 0.5107
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8629 - loss: 0.4738 - val_accuracy: 0.8235 - val_loss: 0.5057
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8662 - loss: 0.4691 - val_accuracy: 0.8235 - val_loss: 0.5003
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8662 - loss: 0.4643 - val_accuracy: 0.8235 - val_loss: 0.4957
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8662 - loss: 0.4591 - val_accuracy: 0.8235 - val_loss: 0.4902
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8629 - loss: 0.4546 - val_accuracy: 0.8235 - val_loss: 0.4854
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8629 - loss: 0.4496 - val_accuracy: 0.8235 - val_loss: 0.4807
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8662 - loss: 0.4452 - val_accuracy: 0.8235 - val_loss: 0.4758
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8662 - loss: 0.4404 - val_accuracy: 0.8235 - val_loss: 0.4711
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8629 - loss: 0.4360 - val_accuracy: 0.8235 - val_loss: 0.4667
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8696 - loss: 0.4318 - val_accuracy: 0.8235 - val_loss: 0.4624
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8696 - loss: 0.4271 - val_accuracy: 0.8235 - val_loss: 0.4576
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8629 - loss: 0.4236 - val_accuracy: 0.8235 - val_loss: 0.4536
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8696 - loss: 0.4188 - val_accuracy: 0.8235 - val_loss: 0.4501
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8696 - loss: 0.4146 - val_accuracy: 0.8235 - val_loss: 0.4460
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8696 - loss: 0.4103 - val_accuracy: 0.8235 - val_loss: 0.4423
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8662 - loss: 0.4063 - val_accuracy: 0.8235 - val_loss: 0.4378
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8729 - loss: 0.4026 - val_accuracy: 0.8529 - val_loss: 0.4336
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8662 - loss: 0.3993 - val_accuracy: 0.8529 - val_loss: 0.4298
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8696 - loss: 0.3944 - val_accuracy: 0.8529 - val_loss: 0.4267
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8729 - loss: 0.3905 - val_accuracy: 0.8235 - val_loss: 0.4252
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8796 - loss: 0.3872 - val_accuracy: 0.8529 - val_loss: 0.4192
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8696 - loss: 0.3836 - val_accuracy: 0.8235 - val_loss: 0.4172
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8796 - loss: 0.3796 - val_accuracy: 0.8529 - val_loss: 0.4127
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8729 - loss: 0.3755 - val_accuracy: 0.8235 - val_loss: 0.4103
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8796 - loss: 0.3727 - val_accuracy: 0.8529 - val_loss: 0.4055
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8796 - loss: 0.3687 - val_accuracy: 0.8529 - val_loss: 0.4028
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3652 - val_accuracy: 0.8529 - val_loss: 0.4008
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8796 - loss: 0.3613 - val_accuracy: 0.8529 - val_loss: 0.3965
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8796 - loss: 0.3582 - val_accuracy: 0.8529 - val_loss: 0.3923
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8829 - loss: 0.3549 - val_accuracy: 0.8529 - val_loss: 0.3904
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3513 - val_accuracy: 0.8529 - val_loss: 0.3866
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3489 - val_accuracy: 0.8529 - val_loss: 0.3871
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3458 - val_accuracy: 0.8529 - val_loss: 0.3822
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3431 - val_accuracy: 0.8529 - val_loss: 0.3804
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8829 - loss: 0.3395 - val_accuracy: 0.8529 - val_loss: 0.3774
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3358 - val_accuracy: 0.8529 - val_loss: 0.3747
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8796 - loss: 0.3346 - val_accuracy: 0.8529 - val_loss: 0.3714
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8829 - loss: 0.3303 - val_accuracy: 0.8529 - val_loss: 0.3710
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3280 - val_accuracy: 0.8529 - val_loss: 0.3670
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3249 - val_accuracy: 0.8529 - val_loss: 0.3666
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3217 - val_accuracy: 0.8529 - val_loss: 0.3618
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3190 - val_accuracy: 0.8529 - val_loss: 0.3579
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3168 - val_accuracy: 0.8529 - val_loss: 0.3569
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3140 - val_accuracy: 0.8529 - val_loss: 0.3552
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3108 - val_accuracy: 0.8529 - val_loss: 0.3510
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3088 - val_accuracy: 0.8529 - val_loss: 0.3502
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8829 - loss: 0.3056 - val_accuracy: 0.8529 - val_loss: 0.3481
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3036 - val_accuracy: 0.8824 - val_loss: 0.3447
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.3014 - val_accuracy: 0.8824 - val_loss: 0.3429
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8829 - loss: 0.2980 - val_accuracy: 0.8824 - val_loss: 0.3421
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2956 - val_accuracy: 0.8529 - val_loss: 0.3380
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2929 - val_accuracy: 0.8824 - val_loss: 0.3363
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8829 - loss: 0.2917 - val_accuracy: 0.8824 - val_loss: 0.3355
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2886 - val_accuracy: 0.8529 - val_loss: 0.3314
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8829 - loss: 0.2857 - val_accuracy: 0.8824 - val_loss: 0.3286
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2840 - val_accuracy: 0.8824 - val_loss: 0.3276
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2817 - val_accuracy: 0.8529 - val_loss: 0.3241
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2810 - val_accuracy: 0.8529 - val_loss: 0.3232
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2783 - val_accuracy: 0.8529 - val_loss: 0.3219
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2754 - val_accuracy: 0.8529 - val_loss: 0.3198
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8829 - loss: 0.2745 - val_accuracy: 0.8824 - val_loss: 0.3184
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2716 - val_accuracy: 0.8824 - val_loss: 0.3161
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8829 - loss: 0.2696 - val_accuracy: 0.8824 - val_loss: 0.3151
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8829 - loss: 0.2678 - val_accuracy: 0.8824 - val_loss: 0.3119
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8829 - loss: 0.2655 - val_accuracy: 0.8824 - val_loss: 0.3099
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2634 - val_accuracy: 0.8824 - val_loss: 0.3092
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2622 - val_accuracy: 0.8824 - val_loss: 0.3069
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2596 - val_accuracy: 0.8824 - val_loss: 0.3049
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8829 - loss: 0.2576 - val_accuracy: 0.8529 - val_loss: 0.3029
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8863 - loss: 0.2550 - val_accuracy: 0.8824 - val_loss: 0.3010
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8829 - loss: 0.2544 - val_accuracy: 0.8824 - val_loss: 0.2986
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2514 - val_accuracy: 0.8824 - val_loss: 0.2968
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2518 - val_accuracy: 0.8824 - val_loss: 0.2958
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2476 - val_accuracy: 0.8824 - val_loss: 0.2938
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2458 - val_accuracy: 0.8824 - val_loss: 0.2924
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8863 - loss: 0.2441 - val_accuracy: 0.8824 - val_loss: 0.2892
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8863 - loss: 0.2437 - val_accuracy: 0.8824 - val_loss: 0.2882
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8829 - loss: 0.2413 - val_accuracy: 0.8824 - val_loss: 0.2856
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8863 - loss: 0.2396 - val_accuracy: 0.8824 - val_loss: 0.2850
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8896 - loss: 0.2385 - val_accuracy: 0.8824 - val_loss: 0.2826
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8896 - loss: 0.2357 - val_accuracy: 0.8824 - val_loss: 0.2811
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8896 - loss: 0.2347 - val_accuracy: 0.8824 - val_loss: 0.2792
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8930 - loss: 0.2335 - val_accuracy: 0.8824 - val_loss: 0.2771
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8896 - loss: 0.2319 - val_accuracy: 0.8824 - val_loss: 0.2766
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8896 - loss: 0.2299 - val_accuracy: 0.8824 - val_loss: 0.2745
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8896 - loss: 0.2284 - val_accuracy: 0.8824 - val_loss: 0.2736
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8930 - loss: 0.2273 - val_accuracy: 0.8824 - val_loss: 0.2719
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8963 - loss: 0.2260 - val_accuracy: 0.8824 - val_loss: 0.2702
11/11 - 0s - 2ms/step - accuracy: 0.8949 - loss: 0.2283

In [11]:
model_logit_true = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_true.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_true.fit(
    scaled_penguins_x, penguins_y, batch_size=64, epochs=100, validation_split=0.1
)

scores = model_logit_true.evaluate(scaled_penguins_x, penguins_y, verbose=2)

Epoch 1/100

C:\miniforge3\envs\machine-learning\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9097 - loss: 0.2246 - val_accuracy: 0.9118 - val_loss: 0.2680
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9231 - loss: 0.2204 - val_accuracy: 0.9118 - val_loss: 0.2654
Epoch 3/100
1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8906 - loss: 0.2458

C:\miniforge3\envs\machine-learning\Lib\site-packages\keras\src\backend\tensorflow\nn.py:1216: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9298 - loss: 0.2199 - val_accuracy: 0.9412 - val_loss: 0.2638
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9298 - loss: 0.2174 - val_accuracy: 0.9412 - val_loss: 0.2622
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9264 - loss: 0.2151 - val_accuracy: 0.9412 - val_loss: 0.2604
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9298 - loss: 0.2140 - val_accuracy: 0.9412 - val_loss: 0.2583
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9298 - loss: 0.2125 - val_accuracy: 0.9412 - val_loss: 0.2571
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9331 - loss: 0.2113 - val_accuracy: 0.9412 - val_loss: 0.2558
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9298 - loss: 0.2096 - val_accuracy: 0.9412 - val_loss: 0.2545
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9331 - loss: 0.2081 - val_accuracy: 0.9412 - val_loss: 0.2530
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9331 - loss: 0.2070 - val_accuracy: 0.9412 - val_loss: 0.2514
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9264 - loss: 0.2065 - val_accuracy: 0.9412 - val_loss: 0.2508
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9365 - loss: 0.2048 - val_accuracy: 0.9412 - val_loss: 0.2490
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9398 - loss: 0.2026 - val_accuracy: 0.9412 - val_loss: 0.2480
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9398 - loss: 0.2023 - val_accuracy: 0.9412 - val_loss: 0.2461
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9264 - loss: 0.2021 - val_accuracy: 0.9412 - val_loss: 0.2450
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9365 - loss: 0.2001 - val_accuracy: 0.9412 - val_loss: 0.2440
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9331 - loss: 0.1989 - val_accuracy: 0.9412 - val_loss: 0.2433
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9398 - loss: 0.1975 - val_accuracy: 0.9412 - val_loss: 0.2423
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9365 - loss: 0.1965 - val_accuracy: 0.9412 - val_loss: 0.2407
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9365 - loss: 0.1957 - val_accuracy: 0.9412 - val_loss: 0.2399
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9398 - loss: 0.1938 - val_accuracy: 0.9412 - val_loss: 0.2382
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9365 - loss: 0.1928 - val_accuracy: 0.9412 - val_loss: 0.2372
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9398 - loss: 0.1924 - val_accuracy: 0.9412 - val_loss: 0.2360
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9398 - loss: 0.1903 - val_accuracy: 0.9412 - val_loss: 0.2345
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9398 - loss: 0.1891 - val_accuracy: 0.9412 - val_loss: 0.2341
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9365 - loss: 0.1893 - val_accuracy: 0.9412 - val_loss: 0.2326
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9365 - loss: 0.1890 - val_accuracy: 0.9412 - val_loss: 0.2306
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9365 - loss: 0.1863 - val_accuracy: 0.9412 - val_loss: 0.2290
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9365 - loss: 0.1865 - val_accuracy: 0.9412 - val_loss: 0.2281
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9398 - loss: 0.1842 - val_accuracy: 0.9412 - val_loss: 0.2277
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9398 - loss: 0.1847 - val_accuracy: 0.9412 - val_loss: 0.2262
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9398 - loss: 0.1831 - val_accuracy: 0.9412 - val_loss: 0.2259
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9398 - loss: 0.1814 - val_accuracy: 0.9412 - val_loss: 0.2241
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9398 - loss: 0.1803 - val_accuracy: 0.9412 - val_loss: 0.2230
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9398 - loss: 0.1800 - val_accuracy: 0.9412 - val_loss: 0.2229
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9431 - loss: 0.1801 - val_accuracy: 0.9412 - val_loss: 0.2216
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9398 - loss: 0.1775 - val_accuracy: 0.9412 - val_loss: 0.2200
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9398 - loss: 0.1768 - val_accuracy: 0.9412 - val_loss: 0.2193
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9365 - loss: 0.1763 - val_accuracy: 0.9412 - val_loss: 0.2176
Epoch 41/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9365 - loss: 0.1759 - val_accuracy: 0.9412 - val_loss: 0.2169
Epoch 42/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9398 - loss: 0.1738 - val_accuracy: 0.9412 - val_loss: 0.2161
Epoch 43/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9398 - loss: 0.1737 - val_accuracy: 0.9412 - val_loss: 0.2147
Epoch 44/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9398 - loss: 0.1735 - val_accuracy: 0.9412 - val_loss: 0.2131
Epoch 45/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9365 - loss: 0.1717 - val_accuracy: 0.9412 - val_loss: 0.2127
Epoch 46/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9365 - loss: 0.1716 - val_accuracy: 0.9412 - val_loss: 0.2122
Epoch 47/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9365 - loss: 0.1704 - val_accuracy: 0.9412 - val_loss: 0.2109
Epoch 48/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9398 - loss: 0.1702 - val_accuracy: 0.9412 - val_loss: 0.2105
Epoch 49/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9398 - loss: 0.1694 - val_accuracy: 0.9412 - val_loss: 0.2098
Epoch 50/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9398 - loss: 0.1681 - val_accuracy: 0.9412 - val_loss: 0.2083
Epoch 51/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9398 - loss: 0.1666 - val_accuracy: 0.9412 - val_loss: 0.2076
Epoch 52/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9398 - loss: 0.1669 - val_accuracy: 0.9412 - val_loss: 0.2075
Epoch 53/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9431 - loss: 0.1648 - val_accuracy: 0.9412 - val_loss: 0.2060
Epoch 54/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9398 - loss: 0.1651 - val_accuracy: 0.9412 - val_loss: 0.2047
Epoch 55/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9431 - loss: 0.1647 - val_accuracy: 0.9412 - val_loss: 0.2048
Epoch 56/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9431 - loss: 0.1625 - val_accuracy: 0.9412 - val_loss: 0.2037
Epoch 57/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9365 - loss: 0.1623 - val_accuracy: 0.9412 - val_loss: 0.2018
Epoch 58/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9431 - loss: 0.1614 - val_accuracy: 0.9412 - val_loss: 0.2018
Epoch 59/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9398 - loss: 0.1604 - val_accuracy: 0.9412 - val_loss: 0.2010
Epoch 60/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9398 - loss: 0.1592 - val_accuracy: 0.9412 - val_loss: 0.1996
Epoch 61/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9398 - loss: 0.1595 - val_accuracy: 0.9412 - val_loss: 0.1988
Epoch 62/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9398 - loss: 0.1579 - val_accuracy: 0.9412 - val_loss: 0.1982
Epoch 63/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9431 - loss: 0.1572 - val_accuracy: 0.9412 - val_loss: 0.1974
Epoch 64/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9398 - loss: 0.1551 - val_accuracy: 0.9412 - val_loss: 0.1980
Epoch 65/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9431 - loss: 0.1547 - val_accuracy: 0.9412 - val_loss: 0.1960
Epoch 66/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9465 - loss: 0.1527 - val_accuracy: 0.9412 - val_loss: 0.1947
Epoch 67/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9431 - loss: 0.1508 - val_accuracy: 0.9412 - val_loss: 0.1944
Epoch 68/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9431 - loss: 0.1496 - val_accuracy: 0.9412 - val_loss: 0.1912
Epoch 69/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9465 - loss: 0.1481 - val_accuracy: 0.9412 - val_loss: 0.1912
Epoch 70/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9465 - loss: 0.1475 - val_accuracy: 0.9412 - val_loss: 0.1913
Epoch 71/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9431 - loss: 0.1452 - val_accuracy: 0.9412 - val_loss: 0.1874
Epoch 72/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9498 - loss: 0.1445 - val_accuracy: 0.9412 - val_loss: 0.1856
Epoch 73/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9465 - loss: 0.1424 - val_accuracy: 0.9412 - val_loss: 0.1843
Epoch 74/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9465 - loss: 0.1424 - val_accuracy: 0.9412 - val_loss: 0.1836
Epoch 75/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9565 - loss: 0.1399 - val_accuracy: 0.9412 - val_loss: 0.1822
Epoch 76/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9532 - loss: 0.1386 - val_accuracy: 0.9412 - val_loss: 0.1777
Epoch 77/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9565 - loss: 0.1372 - val_accuracy: 0.9412 - val_loss: 0.1745
Epoch 78/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9532 - loss: 0.1357 - val_accuracy: 0.9412 - val_loss: 0.1705
Epoch 79/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9565 - loss: 0.1335 - val_accuracy: 0.9412 - val_loss: 0.1681
Epoch 80/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9565 - loss: 0.1323 - val_accuracy: 0.9412 - val_loss: 0.1640
Epoch 81/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9565 - loss: 0.1307 - val_accuracy: 0.9412 - val_loss: 0.1616
Epoch 82/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9599 - loss: 0.1290 - val_accuracy: 0.9412 - val_loss: 0.1587
Epoch 83/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9565 - loss: 0.1276 - val_accuracy: 0.9412 - val_loss: 0.1548
Epoch 84/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9599 - loss: 0.1254 - val_accuracy: 0.9412 - val_loss: 0.1542
Epoch 85/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9599 - loss: 0.1243 - val_accuracy: 0.9412 - val_loss: 0.1510
Epoch 86/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9599 - loss: 0.1234 - val_accuracy: 0.9412 - val_loss: 0.1471
Epoch 87/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9565 - loss: 0.1218 - val_accuracy: 0.9412 - val_loss: 0.1470
Epoch 88/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9599 - loss: 0.1193 - val_accuracy: 0.9412 - val_loss: 0.1432
Epoch 89/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9565 - loss: 0.1185 - val_accuracy: 0.9412 - val_loss: 0.1393
Epoch 90/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9599 - loss: 0.1172 - val_accuracy: 0.9412 - val_loss: 0.1437
Epoch 91/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9565 - loss: 0.1176 - val_accuracy: 0.9412 - val_loss: 0.1395
Epoch 92/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9599 - loss: 0.1150 - val_accuracy: 0.9412 - val_loss: 0.1333
Epoch 93/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9565 - loss: 0.1143 - val_accuracy: 0.9412 - val_loss: 0.1312
Epoch 94/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9599 - loss: 0.1125 - val_accuracy: 0.9412 - val_loss: 0.1279
Epoch 95/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9599 - loss: 0.1114 - val_accuracy: 0.9412 - val_loss: 0.1271
Epoch 96/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9632 - loss: 0.1102 - val_accuracy: 0.9706 - val_loss: 0.1235
Epoch 97/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9599 - loss: 0.1093 - val_accuracy: 0.9706 - val_loss: 0.1188
Epoch 98/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9632 - loss: 0.1070 - val_accuracy: 0.9706 - val_loss: 0.1178
Epoch 99/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9632 - loss: 0.1071 - val_accuracy: 0.9706 - val_loss: 0.1178
Epoch 100/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9666 - loss: 0.1051 - val_accuracy: 0.9706 - val_loss: 0.1147
11/11 - 0s - 3ms/step - accuracy: 0.9670 - loss: 0.1045